In [2]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import expit as sigmoid
import math
%matplotlib inline
import cPickle
data = cPickle.load(open("data.pk", "rb"))

In [3]:
data

{'test_inputs': array([[182,  89, 186],
        [ 42,  67, 242],
        [ 67, 242,  22],
        ..., 
        [141, 108, 176],
        [108, 176,  22],
        [176,  22, 217]], dtype=int32),
 'test_targets': array([143,  22,  54, ...,  22, 217, 191], dtype=int32),
 'train_inputs': array([[ 27,  25,  89],
        [183,  43, 248],
        [182,  31,  75],
        ..., 
        [ 43,  58,  75],
        [ 27,  25,  35],
        [ 75, 122, 223]], dtype=int32),
 'train_targets': array([143, 116, 121, ...,  46, 192, 143], dtype=int32),
 'valid_inputs': array([[169, 136, 189],
        [136, 189, 142],
        [189, 142,  58],
        ..., 
        [249, 175,  25],
        [175,  25, 248],
        [ 25, 248, 131]], dtype=int32),
 'valid_targets': array([142,  58, 139, ..., 248, 131, 143], dtype=int32),
 'vocab': [u'all',
  u'set',
  u'just',
  u'show',
  u'being',
  u'money',
  u'over',
  u'both',
  u'years',
  u'four',
  u'through',
  u'during',
  u'go',
  u'still',
  u'children',
  u'befor

In [26]:
z.T

array([[1],
       [2],
       [3],
       [4]])

In [32]:
z = np.array([[1, 2, 3, 4]])

In [34]:
z.T.sum(0).reshape((-1,1))

array([[10]])

In [35]:
z.T.sum(0)

array([10])